### ISSUE TITLE
Why is image coordinate multiplied by 2 when generating sampling_maps

### ISSUE THREAD

**Issue by ghost** [intel-isl/FreeViewSynthesis#17]
Hi @griegler,

When I look into preprocess.cpp to understand how sampling maps are computed, I could not understand why the image coordinate (src_wf, src_wh) is multiplied by 2 in [https://github.com/intel-isl/FreeViewSynthesis/blob/master/ext/preprocess/preprocess.cpp#L262-L263](https://github.com/intel-isl/FreeViewSynthesis/blob/master/ext/preprocess/preprocess.cpp#L262-L263). Is there any specific reason to do that? Would you mind to share a few detail on it? Thanks. 

 .

**Comment by griegler** [comment]
Because the maps are used in [`grid_sample`](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.grid_sample) which expects the map values to be in the range of `[-1,1]`.  `src_wf / (src_width - 1)` transforms it to the range `[0,1]`, `2 * x - 1` transforms it to the range `[-1,1]`.

**Comment by ghost** [comment]
Thank you for the response. It is very clear to me now.
