### ISSUE TITLE
Proxy-geometry generation pipeline

### ISSUE THREAD

**Issue by shubham-goel** [intel-isl/FreeViewSynthesis#22]
Hi, This is great work!! Thank you for making your code public :)

I'm trying to use your proxy-geometry generation pipeline using the scripts in `co/colmap.py` but am not a 100% sure I'm doing it right. Is this how you generated the meshes in your paper? Thanks in advance!

```python
colmap = Colmap(...)
colmap.sparse_reconstruction_unknown_calib()
colmap.dense_reconstruction()
colmap.delaunay_meshing()
```

**Comment by griegler** [comment]
Yes, if you want to include all images in your reconstruction. If you want to keep certain images aside for testing, you would have to run `sparse_reconstruction_unknown_calib` first und then use `sparse_reconstruction_unknown_calib` using only the images/poses that should be included in the source set. The rest remains the same.

**Comment by shubham-goel** [comment]
Thank you!

**Comment by Xiaoming-Zhao** [comment]
@griegler Hi Gernot, thanks a lot for your great work. I have a follow-up question regarding the mesh reconstruction. As you mentioned
> then use `sparse_reconstruction_unknown_calib` using only the images/poses that should be included in the source set. The rest remains the same.

I am wondering how you undistort all images? Since `image_undistorter` is called under `dense_reconstruction`, does it mean that evaluation images will not be undistorted? If this is not the case, can I know what your pipeline is to undistort all of them? Thanks a lot in advance.

https://github.com/intel-isl/FreeViewSynthesis/blob/33a31ee214a77a2fa074d3a10cedc09803ec2ceb/co/colmap.py#L864-L867
